### ISSUE TITLE
ERROR: missed type id XXXX and wrong result

### ISSUE THREAD

**Issue by jczhang07** [lvc/abi-dumper#21]
Under my Linux (CentOS-7), I built my library with -g -Og, and then dump the ABI.
After a lot of "ERROR: missed type id XXXX", it did generate the abi dump. But I saw may strange things like   'Header' => undef in the dump file. 
Comparing dumps of two versions of the library with abi-compliance-checker.pl gives me "compatibility: 100%". Actually, it is not true.

**Comment by minglumlu** [comment]
I hit this also when I used the `abi-dumper` released by CentOS 7. So I used the latest `abi-dumper` from the master branch. Then the error disappeared.

**Comment by lvc** [comment]
> Under my Linux (CentOS-7), I built my library with -g -Og, and then dump the ABI.
> After a lot of "ERROR: missed type id XXXX", it did generate the abi dump. But I saw may strange things like 'Header' => undef in the dump file.
> Comparing dumps of two versions of the library with abi-compliance-checker.pl gives me "compatibility: 100%". Actually, it is not true.

Please use latest master version.

Also add `-lambda` extra option to avoid such errors for code using lambda expressions.

**Comment by WardF** [comment]
I am seeing this in the latest `master` version on 64-bit Ubuntu 20.04. I'm happy to provide any additional information re: my environment, as it would help.

Update: I was seeing this with the abi-dumper installed via `lvc-installer`; installing abi-dumper explicitly from the github repo solved the issue.

**Comment by lvc** [comment]
Probably it's time to release 1.2 with latest fixes included.

**Comment by kyrofa** [comment]
We're getting bit by this as well, a new release would be much appreciated, @lvc.

**Comment by arnisjuraga** [comment]
Use of latest master branch 3d6dbb6d48d10579984fb7fda2e79d3d73e10f70 helped.

**Comment by lvc** [comment]
Released 1.2

**Comment by kyrofa** [comment]
Thank you @lvc, much appreciated.
