### ISSUE TITLE
ERROR: can't find "eu-readelf" from Elfutils

### ISSUE THREAD

**Issue by MatthewSloyan** [lvc/abi-dumper#26]
Hi, I am trying to use abi-dumper but I am encountering the following error "ERROR: can't find "eu-readelf" from Elfutils".

I have installed the elfutils into a custom location but I don't know how to point the abi-dumper tool to it? I've also tried adding it to the LD_LIBRARY_PATH. Would you have any ideas? It works if I install Elfutils into the default system usr/ directory however it needs to be in a specified location.

Thanks in advance for your help!

**Comment by linuxhw** [comment]
Hi

Just add it to your `PATH` environment variable:

    export PATH=$PATH:/your/local/bin
    abi-dumper ...

**Comment by MatthewSloyan** [comment]
Thank you, I appreciate your reply!
