### ISSUE TITLE
is abi-dumper workable on Windows version dlls

### ISSUE THREAD

**Issue by zhuda** [lvc/abi-dumper#8]
Hi @lvc , I want know if abi-dumper can create abidump for windows dlls? this way is more easy than descriptor way when using ABI checker, so I would like to know the feasibility.

Thank you!

**Comment by zhuda** [comment]
@ can you give some feedback? Thank you very much!

**Comment by lvc** [comment]
Hi,

The tool dumps ELF objects only. It doesn't work on PE binaries. But I have some plans on the future to create similar tool for Windows.

Thank you.
